version: "{build}"

branches:
  except:
    - /^travis.*$/

clone_depth: 10

os: Visual Studio 2015

platform: 
  - Win32
  - x64

configuration:
  - Debug
  - Release

cache:
  - ci_deps_win_v01.zip

environment:
  # Update dependencies here: https://github.com/coelckers/gzdoom/releases/tag/ci_deps
  DEPS_URL: https://github.com/coelckers/gzdoom/releases/download/ci_deps/
  DEPS_FILENAME: ci_deps_win_v01.zip

install:
  - if not exist "%DEPS_FILENAME%"
    appveyor DownloadFile "%DEPS_URL%%DEPS_FILENAME%"
  - 7z x -y "%DEPS_FILENAME%"

before_build:
  - md build
  - cd build
  - if "%PLATFORM%"=="Win32" set CMAKE_GENERATOR_NAME=Visual Studio 14 2015
  - if "%PLATFORM%"=="x64"   set CMAKE_GENERATOR_NAME=Visual Studio 14 2015 Win64
  - set DEPS_INCLUDE_DIR=%APPVEYOR_BUILD_FOLDER%\ci_deps_win\include
  - set DEPS_LIB_DIR=%APPVEYOR_BUILD_FOLDER%\ci_deps_win\lib\%PLATFORM%
  - cmake -G "%CMAKE_GENERATOR_NAME%" -T "v140_xp"
    -DCMAKE_BUILD_TYPE="%CONFIGURATION%"
    -DFMOD_INCLUDE_DIR="%DEPS_INCLUDE_DIR%"
    -DFMOD_LIBRARY="%DEPS_LIB_DIR%\fmodex.lib"
    -DOPENAL_INCLUDE_DIR="%DEPS_INCLUDE_DIR%"
    -DOPENAL_LIBRARY="%DEPS_LIB_DIR%\OpenAL32.lib"
    -DMPG123_INCLUDE_DIR="%DEPS_INCLUDE_DIR%"
    -DMPG123_LIBRARIES="%DEPS_LIB_DIR%\libmpg123-0.lib"
    -DSNDFILE_INCLUDE_DIR="%DEPS_INCLUDE_DIR%"
    -DSNDFILE_LIBRARY="%DEPS_LIB_DIR%\libsndfile-1.lib"
    ..

build:
  project: build\GZDoom.sln
  parallel: true
  verbosity: minimal

notifications:
  - provider: Email
    on_build_success: false
    on_build_failure: false
    on_build_status_changed: false
